version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - postgres
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env

  prod_db_postgres:
    image: postgres:16.1
    container_name: prod_db_postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  db_test_postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_HOST=db_test_postgres
      - POSTGRES_DB=test_sga
      - POSTGRES_USER=test_sgauser
      - POSTGRES_PASSWORD=K62c.8£Y2x&T
      - POSTGRES_PORT=5432
    container_name: db_test_postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  hiringtestsga:
    image: hiringtestsga
    container_name: hiringtestsga
    env_file:
      - docker.env
    ports:
      - "8000:8000"
    depends_on:
      - prod_db_postgres
      - db_test_postgres
      - redis
      - rabbitmq
    networks:
      - postgres

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
